kind: pipeline
name: default

steps:
- name: build
  image: nginx
  commands:
  - echo "building..."
- name: publish
  image: plugins/docker
  settings:
    username:
    password:
    repo: krishi0408/nginxhelloworld
    tags: "test_1"
