kind: pipeline
name: default

steps:
- name: build
  image: nginx
  commands:
  - echo "building..."
- name: publish
  image: plugins/docker
  settings:
      from_secret: u_docker
      from_secret: p_docker
    repo: krishi0408/nginxhelloworld
    tags: "test_1"
